const SUPABASE_URL = "https://cwehahuxcupodqklxaal.supabase.co";
const SUPABASE_KEY = "sb_publishable_0dVqqdCdDrFgqRfh7E1DvQ_uhJvj1Bh";
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const $ = s => document.querySelector(s);
const money = n => `$${Number(n||0).toFixed(2)}`;
const today = () => new Date().toISOString().slice(0,10);
const esc = (s="") => String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let db={clients:[],memberships:[],products:[],sales:[],expenses:[],classes:[],team:[]}, page="dashboard", cart=[], session=null, profile=null, scheduleWeekOffset=0;

function authScreen(msg=""){$("#app").innerHTML=`<div class="auth-shell"><div class="auth-card"><div class="auth-brand">CORE THEORY<small>STUDIO MANAGER</small></div><h2 style="margin-top:28px">Sign in</h2><p class="muted">Use your Core Theory owner account.</p><form id="loginForm"><label>Email</label><input id="loginEmail" type="email" autocomplete="email" required><label>Password</label><input id="loginPassword" type="password" autocomplete="current-password" required><button class="btn primary" style="width:100%;margin-top:22px" type="submit">Sign in</button><div id="authError" class="auth-error">${esc(msg)}</div></form><div class="auth-note">Your studio data is stored in your Supabase cloud database and protected by login.</div></div></div>`;$("#loginForm").onsubmit=login}
async function login(e){e.preventDefault();$("#authError").textContent="Signing in…";const {data,error}=await sb.auth.signInWithPassword({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value});if(error)return $("#authError").textContent=error.message;session=data.session;await loadAll()}
async function logout(){await sb.auth.signOut();session=null;profile=null;authScreen()}
function isOwner(){return profile?.role==="owner"}
async function loadAll(){
  $("#app").innerHTML='<div class="loading">Loading Core Theory…</div>';
  const {data:p,error:pe}=await sb.from("profiles").select("*").eq("id",session.user.id).single();
  if(pe){authScreen("Profile error: "+pe.message);return}
  profile=p;
  const owner=profile?.role==="owner";
  const tables=owner?["clients","memberships","products","sales","expenses","classes","team"]:["clients","memberships","sales","expenses","classes"];
  db={clients:[],memberships:[],products:[],sales:[],expenses:[],classes:[],team:[]};
  const results=await Promise.all(tables.map(t=>sb.from(t).select("*")));
  const err=results.find(r=>r.error);
  if(err){authScreen("Database error: "+err.error.message);return}
  tables.forEach((t,i)=>db[t]=results[i].data||[]);
  if(!owner && !["schedule","clients","payment","expenses","account"].includes(page)) page="schedule";
  render()
}
function nav(){const pages=isOwner()?["dashboard","clients","schedule","pos","memberships","inventory","expenses","finance","team","settings"]:["schedule","clients","payment","expenses","account"];const labels={dashboard:"⌂ Dashboard",clients:"◎ Clients",schedule:"□ Weekly Schedule",pos:"$ POS / Sales",payment:"$ Record Payment",memberships:"◇ Memberships",inventory:"▣ Inventory",expenses:"− Expenses",finance:"↗ Finance",team:"◌ Team",settings:"⚙ Settings",account:"⚙ Account"};return pages.map(x=>`<button data-page="${x}" class="${page===x?"active":""}">${labels[x]}</button>`).join("")}
function totals(){const rev=db.sales.reduce((a,s)=>a+Number(s.total),0),exp=db.expenses.reduce((a,e)=>a+Number(e.amount),0);return{rev,exp,profit:rev-exp}}
function layout(content,title,subtitle=""){$("#app").innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">CORE THEORY<small>${isOwner()?"Owner":"Instructor"} Portal</small></div><div class="nav">${nav()}</div><div class="role-chip">${esc(profile?.full_name||profile?.email||"")}<small>${isOwner()?"Owner":"Instructor"}</small></div><button class="btn logout" onclick="logout()">Log out</button></aside><main class="main"><div class="topbar"><div><h1>${title}</h1><p>${subtitle}</p><div class="sync-note">☁ Cloud connected</div></div><button class="btn" onclick="loadAll()">Refresh</button></div>${content}</main></div>`;document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function dashboard(){const t=totals(),low=db.products.filter(p=>Number(p.stock)<=Number(p.minimum_stock)),todays=db.classes.filter(c=>c.class_date===today());layout(`<div class="grid kpis"><div class="card kpi"><div class="label">Revenue</div><div class="value">${money(t.rev)}</div><div class="sub">All recorded sales</div></div><div class="card kpi"><div class="label">Expenses</div><div class="value">${money(t.exp)}</div><div class="sub">Bills, stock, payroll & more</div></div><div class="card kpi"><div class="label">Estimated profit</div><div class="value">${money(t.profit)}</div><div class="sub">Revenue − expenses</div></div><div class="card kpi"><div class="label">Clients</div><div class="value">${db.clients.length}</div><div class="sub">${db.products.length} inventory items</div></div></div><div class="spacer"></div><div class="grid two"><div class="card"><h3>Today's classes</h3>${todays.length?todays.map(c=>`<div class="cart-row"><span><b>${esc((c.class_time||"").slice(0,5))}</b> ${esc(c.class_type)}</span><span>${esc(c.instructor||"")} · ${c.booked||0}/${c.capacity||0}</span></div>`).join(""):'<div class="empty">No classes scheduled today.</div>'}</div><div class="card"><h3>Low stock</h3>${low.length?low.map(p=>`<div class="cart-row"><span>${esc(p.name)}</span><span class="badge low">${p.stock} left</span></div>`).join(""):'<div class="empty">Stock levels look good.</div>'}</div></div>`,"Dashboard","Your studio at a glance")}
function clients(){const body=db.clients.length?`<table><thead><tr><th>Client</th><th>Phone</th><th>Package</th><th>Sessions</th><th>Expiry</th>${isOwner()?"<th></th>":""}</tr></thead><tbody>${db.clients.map(c=>`<tr><td><b>${esc(c.name)}</b><div class="muted">${esc(c.email||"")}</div></td><td>${esc(c.phone||"")}</td><td>${esc(c.package||"—")}</td><td>${c.sessions??0}</td><td>${esc(c.expiry||"—")}</td>${isOwner()?`<td><button class="btn small" onclick="useSession('${c.id}')">Use session</button> <button class="btn small" onclick="sellMembership('${c.id}')">Add package</button> <button class="btn small danger" onclick="removeItem('clients','${c.id}')">Delete</button></td>`:""}</tr>`).join("")}</tbody></table>`:'<div class="empty">No clients yet.</div>';layout(`<div class="card">${isOwner()?'<div class="toolbar"><button class="btn primary" onclick="clientModal()">+ Add client</button></div>':""}${body}</div>`,"Clients",isOwner()?"Packages, attendance and contact details":"Client contact details and package balances")}

function mondayOfWeek(offset=0){const d=new Date();const day=(d.getDay()+6)%7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+(offset*7));return d}
function dateISO(d){return d.toISOString().slice(0,10)}
function schedule(){
  const monday=mondayOfWeek(scheduleWeekOffset), days=[];
  for(let i=0;i<6;i++){const d=new Date(monday);d.setDate(monday.getDate()+i);days.push(d)}
  const dates=new Set(days.map(dateISO));
  const weekClasses=db.classes.filter(c=>dates.has(c.class_date));
  const times=[...new Set(weekClasses.map(c=>(c.class_time||"").slice(0,5)).filter(Boolean))].sort();
  if(!times.length) for(let h=7;h<=20;h++) times.push(String(h).padStart(2,"0")+":00");
  const rows=times.map(time=>`<tr><th class="time-col">${formatTime(time)}</th>${days.map(d=>{const ds=dateISO(d), matches=weekClasses.filter(c=>c.class_date===ds&&(c.class_time||"").slice(0,5)===time);return `<td class="schedule-cell">${matches.map(c=>classCard(c)).join("")}</td>`}).join("")}</tr>`).join("");
  const ownerAdd=isOwner()?`<button class="btn primary" onclick="classModal()">+ Add class</button>`:"";
  layout(`<div class="schedule-tools"><div class="toolbar">${ownerAdd}<button class="btn" onclick="scheduleWeekOffset--;schedule()">← Previous</button><button class="btn" onclick="scheduleWeekOffset=0;schedule()">This week</button><button class="btn" onclick="scheduleWeekOffset++;schedule()">Next →</button></div><div class="week-label">${days[0].toLocaleDateString(undefined,{month:"short",day:"numeric"})} – ${days[5].toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</div></div><div class="card schedule-wrap"><table class="weekly-schedule"><thead><tr><th class="time-col">Time</th>${days.map(d=>`<th>${d.toLocaleDateString(undefined,{weekday:"long"})}<small>${d.toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small></th>`).join("")}</tr></thead><tbody>${rows}</tbody></table></div>`,"Schedule","Weekly timetable — classes at the same time stay together in the same row")
}
function formatTime(t){const [h,m]=t.split(":").map(Number),suffix=h>=12?"PM":"AM",hh=h%12||12;return `${hh}:${String(m).padStart(2,"0")} ${suffix}`}
function classCard(c){return `<div class="class-card" ${isOwner()?`onclick="editClassModal('${c.id}')" title="Click to edit"`:""}><b>${esc(c.class_type||"Class")}</b><span>${esc(c.instructor||"No instructor")}</span><small>${formatTime((c.class_time||"00:00").slice(0,5))} · ${c.booked||0}/${c.capacity||0} booked</small></div>`}

function pos(){const sellables=[...db.memberships.map(m=>({...m,kind:"membership"})),...db.products.map(p=>({...p,kind:"product"}))];layout(`<div class="pos"><div class="card"><h3>Products & packages</h3><div class="product-grid">${sellables.map(p=>`<div class="product" data-kind="${p.kind}" data-id="${p.id}"><b>${esc(p.name)}</b><small>${p.kind==="product"?`${p.stock} in stock`:`${p.sessions===999?"Unlimited":p.sessions+" sessions"}`}</small><div style="margin-top:8px">${money(p.price)}</div></div>`).join("")}</div></div><div class="card"><h3>Current sale</h3>${cart.length?cart.map((x,i)=>`<div class="cart-row"><span>${esc(x.name)}</span><span>${money(x.price)} <button class="btn small" onclick="cart.splice(${i},1);render()">×</button></span></div>`).join(""):'<div class="empty">Tap an item to add it.</div>'}<div class="spacer"></div><label class="muted">Client (optional)</label><select id="saleClient"><option value="">Walk-in</option>${db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select><div class="spacer"></div><label class="muted">Payment</label><select id="payment"><option>Cash</option><option>Card</option><option>Whish</option><option>Transfer</option></select><h2 class="right">${money(cart.reduce((a,x)=>a+Number(x.price),0))}</h2><button class="btn primary" style="width:100%" onclick="checkout()">Complete sale</button></div></div>`,"POS / Sales","Sell memberships, sessions and retail products");document.querySelectorAll(".product[data-id]").forEach(el=>el.onclick=()=>{const src=el.dataset.kind==="product"?db.products:db.memberships;const p=src.find(x=>x.id===el.dataset.id);cart.push({...p,kind:el.dataset.kind});render()})}
function memberships(){layout(`<div class="card"><div class="toolbar"><button class="btn primary" onclick="membershipModal()">+ Add membership</button></div><table><thead><tr><th>Name</th><th>Sessions</th><th>Price</th><th>Validity</th><th></th></tr></thead><tbody>${db.memberships.map(m=>`<tr><td><b>${esc(m.name)}</b></td><td>${m.sessions===999?"Unlimited":m.sessions}</td><td>${money(m.price)}</td><td>${m.validity_days} days</td><td><button class="btn small danger" onclick="removeItem('memberships','${m.id}')">Delete</button></td></tr>`).join("")}</tbody></table></div>`,"Memberships","Create your class packages and validity rules")}
function inventory(){layout(`<div class="grid two"><div class="card"><div class="toolbar"><button class="btn primary" onclick="productModal()">+ Add product</button><button class="btn" onclick="stockPurchaseModal()">Record stock purchase</button></div><table><thead><tr><th>Product</th><th>Cost</th><th>Sell</th><th>Stock</th><th></th></tr></thead><tbody>${db.products.map(p=>`<tr><td><b>${esc(p.name)}</b><div class="muted">${esc(p.category||"")}</div></td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td><span class="badge ${Number(p.stock)<=Number(p.minimum_stock)?"low":"good"}">${p.stock}</span></td><td><button class="btn small danger" onclick="removeItem('products','${p.id}')">Delete</button></td></tr>`).join("")}</tbody></table></div><div class="card"><h3>How stock purchases work</h3><p class="muted">When you buy socks, water or other stock, record the purchase here. The quantity is added to inventory and the total cost is automatically added to Expenses.</p></div></div>`,"Inventory","Retail stock, purchase cost and selling price")}
function expenses(){const rows=isOwner()?db.expenses:db.expenses.filter(e=>e.created_by===session?.user?.id);layout(`<div class="card"><div class="toolbar"><button class="btn primary" onclick="expenseModal()">+ Add expense</button></div>${rows.length?`<table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Payment</th><th>Amount</th>${isOwner()?"<th></th>":""}</tr></thead><tbody>${[...rows].sort((a,b)=>(b.expense_date||"").localeCompare(a.expense_date||"")).map(e=>`<tr><td>${e.expense_date}</td><td>${esc(e.category)}</td><td>${esc(e.description||"")}</td><td>${esc(e.payment_method||"")}</td><td class="money-out">${money(e.amount)}</td>${isOwner()?`<td><button class="btn small danger" onclick="removeItem('expenses','${e.id}')">Delete</button></td>`:""}</tr>`).join("")}</tbody></table>`:'<div class="empty">No expenses recorded here yet.</div>'}</div>`,"Expenses",isOwner()?"Everything your studio pays for":"Add expenses — you only see entries recorded by your account")}
function payment(){layout(`<div class="card compact-card"><h3>Record client payment</h3><p class="muted">Use this when a client pays at the studio. This entry is saved under your account.</p><div class="form"><div class="full"><label>Client</label><select id="payClient"><option value="">Walk-in / Other</option>${db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select></div><div><label>Amount</label><input type="number" step=".01" id="payAmount" placeholder="0.00"></div><div><label>Payment method</label><select id="payMethod"><option>Cash</option><option>Card</option><option>Whish</option><option>Transfer</option></select></div><div class="full"><label>Note</label><input id="payNote" placeholder="Private session, package payment, etc."></div><div class="full"><button class="btn primary" onclick="recordPayment()">Record payment</button></div></div></div>`,"Record Payment","Record a payment without access to studio finance totals")}
async function recordPayment(){const amount=+$("#payAmount").value;if(!(amount>0))return alert("Enter a valid amount.");const note=$("#payNote").value.trim()||"Payment";const {error}=await sb.from("sales").insert({client_id:$("#payClient").value||null,total:amount,payment_method:$("#payMethod").value,items:[{name:note,price:amount,kind:"manual_payment"}],created_by:session.user.id});if(error)return alert(error.message);await loadAll();alert("Payment recorded.")}
function account(){layout(`<div class="card compact-card"><h3>${esc(profile?.full_name||"Instructor")}</h3><p class="muted">${esc(session?.user?.email||"")}</p><div class="account-role">Instructor account</div><p class="muted">You can view the schedule and client package balances, record payments, and add expenses. Studio finances and administrative settings are restricted.</p><button class="btn danger" onclick="logout()">Log out</button></div>`,"Account","Core Theory staff access")}

function finance(){const t=totals(),byCat={};db.expenses.forEach(e=>byCat[e.category]=(byCat[e.category]||0)+Number(e.amount));layout(`<div class="grid three"><div class="card kpi"><div class="label">Revenue</div><div class="value">${money(t.rev)}</div></div><div class="card kpi"><div class="label">Expenses</div><div class="value">${money(t.exp)}</div></div><div class="card kpi"><div class="label">Estimated profit</div><div class="value">${money(t.profit)}</div></div></div><div class="spacer"></div><div class="grid two"><div class="card"><h3>Expenses by category</h3>${Object.keys(byCat).length?Object.entries(byCat).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="cart-row"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join(""):'<div class="empty">No expenses yet.</div>'}</div><div class="card"><h3>Recent sales</h3>${db.sales.length?[...db.sales].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,8).map(s=>`<div class="cart-row"><span>${new Date(s.created_at).toLocaleString()} · ${esc(s.payment_method||"")}</span><b>${money(s.total)}</b></div>`).join(""):'<div class="empty">No sales yet.</div>'}</div></div>`,"Finance","Revenue − expenses = estimated profit")}
function team(){layout(`<div class="card"><div class="toolbar"><button class="btn primary" onclick="teamModal()">+ Add team member</button></div>${db.team.length?`<table><thead><tr><th>Name</th><th>Role</th><th>Phone</th><th>Rate / commission</th><th></th></tr></thead><tbody>${db.team.map(t=>`<tr><td><b>${esc(t.name)}</b></td><td>${esc(t.role||"")}</td><td>${esc(t.phone||"")}</td><td>${esc(t.rate||"")}</td><td><button class="btn small danger" onclick="removeItem('team','${t.id}')">Delete</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">Add instructors or staff.</div>'}</div>`,"Team","Instructors, staff and pay notes")}
function settings(){layout(`<div class="grid two"><div class="card"><h3>Core Theory</h3><p class="muted">Your website is connected to Supabase cloud storage. Data entered on one signed-in device is available on your other devices.</p><button class="btn" onclick="loadAll()">Refresh cloud data</button></div><div class="card"><h3>Account</h3><p class="muted">Signed in as ${esc(session?.user?.email||"")}</p><button class="btn danger" onclick="logout()">Log out</button></div></div>`,"Settings","Cloud connection and account")}
function render(){const pages={dashboard,clients,schedule,pos,payment,memberships,inventory,expenses,finance,team,settings,account};if(!isOwner() && !["schedule","clients","payment","expenses","account"].includes(page))page="schedule";(pages[page]||schedule)()}
function modal(title,body){document.body.insertAdjacentHTML("beforeend",`<div class="modal-wrap" id="modal"><div class="modal"><div class="row" style="justify-content:space-between"><h2>${title}</h2><button class="btn" onclick="$('#modal').remove()">×</button></div>${body}</div></div>`)}
function clientModal(){modal("Add client",`<div class="form"><div><label>Name</label><input id="cname"></div><div><label>Phone</label><input id="cphone"></div><div><label>Email</label><input id="cemail"></div><div class="full"><label>Notes</label><textarea id="cnotes"></textarea></div><div class="full"><button class="btn primary" onclick="addClient()">Save client</button></div></div>`)}
async function addClient(){const {error}=await sb.from("clients").insert({name:$("#cname").value,phone:$("#cphone").value,email:$("#cemail").value,notes:$("#cnotes").value,sessions:0});if(error)return alert(error.message);$("#modal").remove();await loadAll()}
function classModal(){modal("Add class",`<div class="form"><div><label>Date</label><input type="date" id="cldate" value="${today()}"></div><div><label>Time</label><input type="time" id="cltime"></div><div><label>Class name</label><input id="cltype" placeholder="Rise & Shine / Reformer / Lagree"></div><div><label>Instructor</label><input id="clinstructor"></div><div><label>Capacity</label><input type="number" id="clcap" value="10"></div><div><label>Booked</label><input type="number" id="clbooked" value="0"></div><div class="full"><button class="btn primary" onclick="addClass()">Save class</button></div></div>`)}
async function addClass(){if(!isOwner())return alert("Only the owner can change the master schedule.");const {error}=await sb.from("classes").insert({class_date:$("#cldate").value,class_time:$("#cltime").value,class_type:$("#cltype").value,instructor:$("#clinstructor").value,capacity:+$("#clcap").value,booked:+$("#clbooked").value});if(error)return alert(error.message);$("#modal").remove();await loadAll()}
function editClassModal(id){if(!isOwner())return;const c=db.classes.find(x=>x.id===id);if(!c)return;modal("Edit class",`<div class="form"><div><label>Date</label><input type="date" id="cldate" value="${esc(c.class_date)}"></div><div><label>Time</label><input type="time" id="cltime" value="${esc((c.class_time||"").slice(0,5))}"></div><div><label>Class name</label><input id="cltype" value="${esc(c.class_type||"")}"></div><div><label>Instructor</label><input id="clinstructor" value="${esc(c.instructor||"")}"></div><div><label>Capacity</label><input type="number" id="clcap" value="${c.capacity||10}"></div><div><label>Booked</label><input type="number" id="clbooked" value="${c.booked||0}"></div><div class="full row"><button class="btn primary" onclick="saveClass('${id}')">Save changes</button><button class="btn danger" onclick="deleteClass('${id}')">Delete class</button></div></div>`)}
async function saveClass(id){const {error}=await sb.from("classes").update({class_date:$("#cldate").value,class_time:$("#cltime").value,class_type:$("#cltype").value,instructor:$("#clinstructor").value,capacity:+$("#clcap").value,booked:+$("#clbooked").value}).eq("id",id);if(error)return alert(error.message);$("#modal").remove();await loadAll()}
async function deleteClass(id){if(!confirm("Delete this class?"))return;const {error}=await sb.from("classes").delete().eq("id",id);if(error)return alert(error.message);$("#modal").remove();await loadAll()}

function membershipModal(){modal("Add membership",`<div class="form"><div><label>Name</label><input id="mname"></div><div><label>Sessions</label><input type="number" id="msessions"></div><div><label>Price</label><input type="number" step=".01" id="mprice"></div><div><label>Validity (days)</label><input type="number" id="mdays" value="30"></div><div class="full"><button class="btn primary" onclick="addMembership()">Save membership</button></div></div>`)}
async function addMembership(){const {error}=await sb.from("memberships").insert({name:$("#mname").value,sessions:+$("#msessions").value,price:+$("#mprice").value,validity_days:+$("#mdays").value});if(error)return alert(error.message);$("#modal").remove();await loadAll()}
function productModal(){modal("Add product",`<div class="form"><div><label>Name</label><input id="pname"></div><div><label>Category</label><input id="pcat" value="Retail"></div><div><label>Cost per unit</label><input type="number" step=".01" id="pcost"></div><div><label>Selling price</label><input type="number" step=".01" id="pprice"></div><div><label>Current stock</label><input type="number" id="pstock" value="0"></div><div><label>Low stock alert</label><input type="number" id="pmin" value="5"></div><div class="full"><button class="btn primary" onclick="addProduct()">Save product</button></div></div>`)}
async function addProduct(){const {error}=await sb.from("products").insert({name:$("#pname").value,category:$("#pcat").value,cost:+$("#pcost").value,price:+$("#pprice").value,stock:+$("#pstock").value,minimum_stock:+$("#pmin").value});if(error)return alert(error.message);$("#modal").remove();await loadAll()}
function expenseModal(){modal("Add expense",`<div class="form"><div><label>Date</label><input type="date" id="edate" value="${today()}"></div><div><label>Category</label><select id="ecat"><option>Electricity</option><option>Rent</option><option>Water</option><option>Internet</option><option>Cleaning</option><option>Payroll</option><option>Inventory</option><option>Marketing</option><option>Maintenance</option><option>Other</option></select></div><div class="full"><label>Description</label><input id="edesc"></div><div><label>Amount</label><input type="number" step=".01" id="eamount"></div><div><label>Payment method</label><select id="epay"><option>Cash</option><option>Card</option><option>Whish</option><option>Transfer</option></select></div><div class="full"><button class="btn primary" onclick="addExpense()">Save expense</button></div></div>`)}
async function addExpense(){const {error}=await sb.from("expenses").insert({expense_date:$("#edate").value,category:$("#ecat").value,description:$("#edesc").value,amount:+$("#eamount").value,payment_method:$("#epay").value,created_by:session.user.id});if(error)return alert(error.message);$("#modal").remove();await loadAll()}
function stockPurchaseModal(){modal("Record stock purchase",`<div class="form"><div class="full"><label>Product</label><select id="spid">${db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select></div><div><label>Quantity bought</label><input type="number" id="spqty"></div><div><label>Total paid</label><input type="number" step=".01" id="sptotal"></div><div><label>Date</label><input type="date" id="spdate" value="${today()}"></div><div><label>Payment</label><select id="sppay"><option>Cash</option><option>Card</option><option>Whish</option><option>Transfer</option></select></div><div class="full"><button class="btn primary" onclick="recordStockPurchase()">Save purchase</button></div></div>`)}
async function recordStockPurchase(){const p=db.products.find(x=>x.id==$("#spid").value),q=+$("#spqty").value,total=+$("#sptotal").value;if(!p||q<=0||total<0)return alert("Enter a valid quantity and total.");let r=await sb.from("products").update({stock:Number(p.stock)+q,cost:total/q}).eq("id",p.id);if(r.error)return alert(r.error.message);r=await sb.from("expenses").insert({expense_date:$("#spdate").value,category:"Inventory",description:`Stock purchase: ${p.name} × ${q}`,amount:total,payment_method:$("#sppay").value});if(r.error)return alert(r.error.message);$("#modal").remove();await loadAll()}
function teamModal(){modal("Add team member",`<div class="form"><div><label>Name</label><input id="tname"></div><div><label>Role</label><input id="trole" placeholder="Instructor"></div><div><label>Phone</label><input id="tphone"></div><div><label>Rate / commission</label><input id="trate" placeholder="$20/class or 30%"></div><div class="full"><button class="btn primary" onclick="addTeam()">Save team member</button></div></div>`)}
async function addTeam(){const {error}=await sb.from("team").insert({name:$("#tname").value,role:$("#trole").value,phone:$("#tphone").value,rate:$("#trate").value});if(error)return alert(error.message);$("#modal").remove();await loadAll()}
async function checkout(){if(!cart.length)return alert("Add something to the sale first.");const clientId=$("#saleClient").value||null,payment=$("#payment").value,total=cart.reduce((a,x)=>a+Number(x.price),0);for(const x of cart){if(x.kind==="product"){if(Number(x.stock)<=0)return alert(`${x.name} is out of stock.`);const r=await sb.from("products").update({stock:Number(x.stock)-1}).eq("id",x.id);if(r.error)return alert(r.error.message)}if(x.kind==="membership"&&clientId){const d=new Date();d.setDate(d.getDate()+Number(x.validity_days));const r=await sb.from("clients").update({package:x.name,sessions:x.sessions,expiry:d.toISOString().slice(0,10)}).eq("id",clientId);if(r.error)return alert(r.error.message)}}const {error}=await sb.from("sales").insert({client_id:clientId,total,payment_method:payment,items:cart.map(x=>({id:x.id,name:x.name,price:x.price,kind:x.kind}))});if(error)return alert(error.message);cart=[];await loadAll();alert("Sale recorded in the cloud.")}
function sellMembership(clientId){modal("Add package to client",`<div class="form"><div class="full"><label>Membership</label><select id="smid">${db.memberships.map(m=>`<option value="${m.id}">${esc(m.name)} — ${money(m.price)}</option>`).join("")}</select></div><div><label>Payment</label><select id="smpay"><option>Cash</option><option>Card</option><option>Whish</option><option>Transfer</option></select></div><div class="full"><button class="btn primary" onclick="confirmMembership('${clientId}')">Sell package</button></div></div>`)}
async function confirmMembership(clientId){const m=db.memberships.find(x=>x.id==$("#smid").value),d=new Date();d.setDate(d.getDate()+Number(m.validity_days));let r=await sb.from("clients").update({package:m.name,sessions:m.sessions,expiry:d.toISOString().slice(0,10)}).eq("id",clientId);if(r.error)return alert(r.error.message);r=await sb.from("sales").insert({client_id:clientId,total:m.price,payment_method:$("#smpay").value,items:[{id:m.id,name:m.name,price:m.price,kind:"membership"}]});if(r.error)return alert(r.error.message);$("#modal").remove();await loadAll()}
async function useSession(id){const c=db.clients.find(c=>c.id===id);if(!c)return;if(c.sessions===999)return alert("Unlimited membership — session count stays unlimited.");if(c.sessions<=0)return alert("This client has no sessions remaining.");const {error}=await sb.from("clients").update({sessions:c.sessions-1}).eq("id",id);if(error)return alert(error.message);await loadAll()}
async function removeItem(table,id){if(!isOwner())return alert("Only the owner can delete records.");if(!confirm("Delete this item?"))return;const {error}=await sb.from(table).delete().eq("id",id);if(error)return alert(error.message);await loadAll()}
async function init(){const {data}=await sb.auth.getSession();session=data.session;if(!session)return authScreen();await loadAll();sb.auth.onAuthStateChange((_event,s)=>{session=s;if(!s)authScreen()})}
init();
